"""Risk metrics."""

from chan_trading.risk.combinatorial_cv import (
    PBOReport,
    probability_of_backtest_overfitting,
)
from chan_trading.risk.metrics import (
    RiskReport,
    annualized_return,
    annualized_volatility,
    deflated_sharpe_ratio,
    gain_to_pain_ratio,
    historical_cvar,
    historical_var,
    information_ratio,
    max_drawdown,
    newey_west_sharpe_tstat,
    newey_west_sharpe_variance,
    omega_ratio,
    parametric_gaussian_var,
    probabilistic_sharpe_ratio,
    profit_factor,
    rolling_sharpe_ratio,
    sharpe_ratio,
    sortino_ratio,
    summarize_risk,
    tail_ratio,
    time_under_water,
)
from chan_trading.risk.monte_carlo import (
    MonteCarloReport,
    block_bootstrap_returns,
    bootstrap_returns,
    parametric_student_t_returns,
    simulate_max_drawdown,
    stationary_bootstrap_returns,
)
from chan_trading.risk.regime import (
    TrendRegimeConfig,
    VolatilityRegimeConfig,
    apply_regime_filter,
    apply_trend_filter,
    detect_trend_regime,
    detect_volatility_regime,
    rolling_volatility_percentile,
)

__all__ = [
    "MonteCarloReport",
    "PBOReport",
    "RiskReport",
    "TrendRegimeConfig",
    "VolatilityRegimeConfig",
    "annualized_return",
    "annualized_volatility",
    "apply_regime_filter",
    "apply_trend_filter",
    "block_bootstrap_returns",
    "bootstrap_returns",
    "deflated_sharpe_ratio",
    "detect_trend_regime",
    "detect_volatility_regime",
    "gain_to_pain_ratio",
    "historical_cvar",
    "historical_var",
    "information_ratio",
    "max_drawdown",
    "newey_west_sharpe_tstat",
    "newey_west_sharpe_variance",
    "omega_ratio",
    "parametric_gaussian_var",
    "parametric_student_t_returns",
    "probabilistic_sharpe_ratio",
    "probability_of_backtest_overfitting",
    "profit_factor",
    "rolling_sharpe_ratio",
    "rolling_volatility_percentile",
    "sharpe_ratio",
    "simulate_max_drawdown",
    "sortino_ratio",
    "stationary_bootstrap_returns",
    "summarize_risk",
    "tail_ratio",
    "time_under_water",
]
